// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA594CVwmlq05_I8M34cEUKwvwt-AXlo0E',
    appId: '1:671257003910:web:80650f7dd3394e0fa78e07',
    messagingSenderId: '671257003910',
    projectId: 'dotaapp-f1a80',
    authDomain: 'dotaapp-f1a80.firebaseapp.com',
    storageBucket: 'dotaapp-f1a80.firebasestorage.app',
    measurementId: 'G-2QJXTX19ND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2HY84eK0GA39Y-Rbefv0NnRhFS5hcv-c',
    appId: '1:671257003910:android:035a5727e614c8d2a78e07',
    messagingSenderId: '671257003910',
    projectId: 'dotaapp-f1a80',
    storageBucket: 'dotaapp-f1a80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0DUJu-aoehJUCPUjJhDtK96x6UT1G0sY',
    appId: '1:671257003910:ios:852289ed1184bbfba78e07',
    messagingSenderId: '671257003910',
    projectId: 'dotaapp-f1a80',
    storageBucket: 'dotaapp-f1a80.firebasestorage.app',
    iosBundleId: 'com.protsenko.opendotaApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0DUJu-aoehJUCPUjJhDtK96x6UT1G0sY',
    appId: '1:671257003910:ios:852289ed1184bbfba78e07',
    messagingSenderId: '671257003910',
    projectId: 'dotaapp-f1a80',
    storageBucket: 'dotaapp-f1a80.firebasestorage.app',
    iosBundleId: 'com.protsenko.opendotaApi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA594CVwmlq05_I8M34cEUKwvwt-AXlo0E',
    appId: '1:671257003910:web:a17ff9bac70f5bfda78e07',
    messagingSenderId: '671257003910',
    projectId: 'dotaapp-f1a80',
    authDomain: 'dotaapp-f1a80.firebaseapp.com',
    storageBucket: 'dotaapp-f1a80.firebasestorage.app',
    measurementId: 'G-B7KYTV7W8L',
  );
}
